//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankApp.Db
{
    using System;
    using System.Collections.Generic;
    
    public partial class CashTransaction
    {
        public int Id { get; set; }
        public Nullable<int> TransactionId { get; set; }
        public string cash { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> C100 { get; set; }
        public Nullable<int> C200 { get; set; }
        public Nullable<int> C500 { get; set; }
        public Nullable<int> C2000 { get; set; }
    
        public virtual Transaction Transaction { get; set; }
    }
}
